name: match_discovery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  image_picker: ^1.0.7
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  flutter_launcher_icons: ^0.14.4
  animate_do: ^4.2.0
  lottie: ^3.3.2
  cloud_firestore: ^5.4.4 
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  firebase_storage: ^12.4.10
  flutter_image_compress: ^2.4.0
  fl_chart: ^0.70.2
  intl: ^0.19.0
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^21.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logof1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logof1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/python/
